### ISSUE TITLE
nv.d3.min.js: Uncaught TypeError: a.dispatch.render_start is not a function

### ISSUE THREAD

**Issue by lggwettmann** [PetrDlouhy/django-admin-charts#15]
Hey guys,

first of all, this seems like a great package and thanks for all the work on this. 

Unfortunately, it's quite difficult getting started with this without any documentation on how to use it:
After installing, migrating and setting up a Dashboard Stats, I can see where the chart should be placed, but I get a JS error in NV D3 (see screenshot).

<img width="955" alt="Screenshot 2020-03-14 19 19 30" src="https://user-images.githubusercontent.com/4527829/76687981-0e6df180-6629-11ea-8eae-0068698f5bd3.png">

What's wrong here and how can I solve this?

**Comment by PetrDlouhy** [comment]
Hi,

you might be the first, that uses this (or at least who did write some feedback) after I derived this from `django-admin-tools-stats` into current state. There might be some hurdles, since you are the first, but I am wiling to help, because I would like more people to use this (and potentially get involved).
There is a documentation for this, and some aspect are described at: https://django-admin-charts.readthedocs.io/en/latest/introduction.html
I would be pleased to add everything, you are missing there.

I have never seen such error as you are having, so it is hard to tell, what might be wrong, especially if I don't know models in your application and `DashboardStats` configuration. Did you try any other chart type different than `Pie`. `Pie` is not very well suited for the type of data, that `DashboardStats` produces (although it does should show charts), try `Bar` or `StackedArea`. Also, please try to open in new tab the Ajax page, that pops out in `network` panel of the dev tools and send here it's content.

**Comment by lggwettmann** [comment]
Hey @PetrDlouhy,

thanks for your fast response and your willingness to help with this (besides keeping this fantastic library alive and rocking). 

I did see the docs you mentioned and they were very helpful. I do miss how to set up charts after the initial installation and coded configuration. Which steps am I supposed to take afterward? (I kind of just created a DashboardStats-instance without fully understanding what I'm doing.

For example, I (tried to) set up a 'New Registrations' DashboardStats-instance based on the default Django user model like this: 
<img width="1423" alt="Screenshot 2020-03-14 23 01 26" src="https://user-images.githubusercontent.com/4527829/76691131-d88c3580-6647-11ea-97ed-9c65409de7d8.png">
<img width="1433" alt="Screenshot 2020-03-14 23 01 34" src="https://user-images.githubusercontent.com/4527829/76691133-da55f900-6647-11ea-91f1-6addb29eb103.png">
and I get the same result like in the screenshot in my first post. 

Attached you can find some screenshots of the dev tools:
<img width="1440" alt="Screenshot 2020-03-14 23 04 54" src="https://user-images.githubusercontent.com/4527829/76691177-77b12d00-6648-11ea-9749-12bc35161e10.png">
<img width="1440" alt="Screenshot 2020-03-14 23 05 55" src="https://user-images.githubusercontent.com/4527829/76691178-797af080-6648-11ea-90e5-7c159f45f68a.png">

Thanks for your time and effort.

**Comment by PetrDlouhy** [comment]
The configuration seems right to me and the returned chart data seems to be valid, so I guess this is some kind of version mismatch with the nvd3 javascript libraries. Did you try to install the exact versions as suggested in docs?
```
BOWER_INSTALLED_APPS = (
    'd3#3.3.13',
    'nvd3#1.7.1',
)
```

**Comment by lggwettmann** [comment]
You were absolutely correct. I only had tried to use NVD3 in version 1.7.1 but using D3 also in 3.3.13 did the trick. Sorry for that, I could have come up with that myself. Thanks for your help!

**Comment by lggwettmann** [comment]
I have other questions, so before I add new issues, I'll just post them here if that's okay with you?

I want to display the charts at the top of the dashboard index and not in the footer. I know how to place them at the top following your admin/index.html-template. But just doing
```
{% block footer %}
{% endblock %}
```
seems like a bad idea cause it would block changes to the admin footer from other apps. Any thoughts on that?

**Comment by PetrDlouhy** [comment]
@Iggwettman Weird, I think, I have written answer to this, but I don't see it here.

- You can either override directly the original `Django` template by `{% extends "admin:admin/index.html" %}` and copy the code (which is not very neat), or you can submit pull request, which would place the charts on top when some settings variable is set.

- Criteria filtering or splitting the charts values. I will try to write some more info into the admin help fields or documentation.

- I am not sure about your settings. Can you add screenshot of the settings? Only time series (Date/DateTime is in x-axis) are currently supported by `django-admin-charts`.

- To get integers on Y axis, you can leave that field blank (which is sufficient for most cases). If you want something special, write there a d3-format (https://github.com/d3/d3-format) value. Like `.2s` for SI suffixed values.

- The X-axis format is defined [https://github.com/PetrDlouhy/django-admin-charts/blob/master/admin_tools_stats/views.py#L26](in the code). It doesn't work yet for all cases sufficiently, because different chart types use those values differently. PRs are welcome here.

**Comment by PetrDlouhy** [comment]
I am closing this. @lggwettmann If you still have some issues, please open new issue reports.
