### ISSUE TITLE
Stats not showing on Admin Index

### ISSUE THREAD

**Issue by josylad** [PetrDlouhy/django-admin-charts#18]
Hi, 
I believe the stats are supposed to show on the Admin Index right?
Because after setting it up by following the docs, the charts doesn't show up but if I go to the Dashboard stats page and click the analytics link, a new window shows up with the charts.

Am I missing something? 
I am using Django 3.0

**Comment by PetrDlouhy** [comment]
Hí,

the analytics page is a new feature, which I added to hide some less used charts to make the admin index faster and cleaner. The analytics page now displays all charts, and admin index should display only charts marked as `visible`.

Otherwise the charts should be displayed on the "vanilla" admin index (or on `django-admin-tools` admin index). Please check, if you haven't got some other apps overriding the admin index page templates, which might be blocking the `django-admin-charts` code from executing.

**Comment by lggwettmann** [comment]
Hey guys,

I'm having the same issues here. I removed Django CMS admin to make sure it doesn't override anything and it still doesn't show up. I have marked the charts as 'visible'. Using Django 2.2.

**Comment by fpghost** [comment]
Same issue here too

**Comment by PetrDlouhy** [comment]
Hi,

I have found the problem and fixed it. The fixed version is now released as `0.20.2`.
