### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by srkunze** [PetrDlouhy/django-admin-charts#35]
Hi everyone,

I found this library and it looks quite cool. After installing and configuration, though, I am a bit lost what should happens next after https://django-admin-charts.readthedocs.io/en/latest/introduction.html#basic-setup-for-django-admin

"http://localhost:8000/admin_tools_stats/" cannot be resolved. Would you care to explain to a newbie what the next step after "Open admin panel, configure Dashboard Stats Criteria & Dashboard Stats respectively" is?

Thanks in advance

PS: I checked the referenced model but nothing changed there as well.

**Comment by tsotnesharvadze** [comment]
Hello, I have same problem.

I make everything and what?

:D

**Comment by PetrDlouhy** [comment]
I will try to extend the documentation based on this.

The "Open admin panel..." sentence should mean, that `django-admin-charts` is configurable through Django admin interface:
![Snímek obrazovky_2022-03-04_17-29-58](https://user-images.githubusercontent.com/156755/156801716-72723e20-bd08-4c5d-a649-677d23aaa992.png)

You will have to add `Dashboard stats` and fill in the apropriate values for your models:
![Snímek obrazovky_2022-03-04_17-31-16](https://user-images.githubusercontent.com/156755/156801945-529ee44f-1480-4ff2-8cdb-5b282fed79d5.png)

The charts should show up directly on root admin page as well as on the new analytics page at `/admin_tools_stats/analytics/`.

You shouldn't expect anything directly on the included page (`/admin_tools_stats/`)in Django, because it includes multiple urls.

**Comment by semics-tech** [comment]
I'm also in a similar place to this. It would be really helpful if you could supply some example charts that can just be imported or generated. Is this something that exists or could be considered?

**Comment by PetrDlouhy** [comment]
@semics-tech The point of this project is, that the charts are highly configurable, so every project could have it's own charts configured according to it's database model.

If you want some pre-configured charts, it should be part of the demoproject.

I aggree that this project should be made more accessible, and I am willing to put some effort into it, but also I don't have much time, so every help is appreciated.

**Comment by PetrDlouhy** [comment]
@semics-tech Also, I think the best way to make this project more accessible is to make the documentation and especially the help texts in the application more helpful. So if you tell me, where exactly are you stuck, I can give you advice and put that info in the documentation/help texts.

**Comment by PetrDlouhy** [comment]
I am closing this issue because it seems the original issue is now resolved.
